### ISSUE TITLE
Error on trending_python.py 

### ISSUE THREAD

**Issue by aminzayer** [cclauss/Ten-lines-or-less#13]
Correct Error in python 3.9
repos = soup.find("ol", class_="repo-list").find_all("a", href=True)
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by aminzayer** [comment]
correct this here
[https://github.com/aminzayer/Ten-lines-or-less/pull/1/files](https://github.com/aminzayer/Ten-lines-or-less/pull/1/files)

**Comment by cclauss** [comment]
% `flake8 . --count --select=E9,F63,F7,F82, --show-source --statistics`
```
./Ten-lines-or-less/trending_python.py:9:9: F821 undefined name 'find_all'
repos = find_all("a", href=True)
        ^
1     F821 undefined name 'find_all'
1
```
