### ISSUE TITLE
in weather_where_you_are speech has non-v3 print calls

### ISSUE THREAD

**Issue by jn0** [cclauss/Ten-lines-or-less#4]
hence, the script fails in python3

**Comment by jn0** [comment]
Plus, that speech require win32com quite abruptly :)

**Comment by jn0** [comment]
https://github.com/michaelgundlach/pyspeech aborted

**Comment by cclauss** [comment]
As `README.md` states "___Many of these scripts require Pythonista___" which has a different speech module than pyspeech.  F-strings are supported in all versions of Python that are supported by the Python Core Team https://devguide.python.org/#status-of-python-branches.  Perhaps you are using a version of Python which is end-of-life.  Our automated tests (esp. flake8) would detect any syntax errors.
